-- MySQL Script generated by MySQL Workbench
-- Sun Dec 26 04:38:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema synergy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema synergy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `synergy` DEFAULT CHARACTER SET utf8 ;
USE `synergy` ;

-- -----------------------------------------------------
-- Table `synergy`.`Air Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `synergy`.`Air Company` (
  `idAir Company` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `company_type` VARCHAR(45) NOT NULL,
  `founded_at` DATE NOT NULL,
  PRIMARY KEY (`idAir Company`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `synergy`.`Airplane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `synergy`.`Airplane` (
  `idAirplane` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `factory_serial_name` INT NOT NULL,
  `number_of_flight` VARCHAR(45) NOT NULL,
  `flight_distance` INT NOT NULL,
  `fuel_capacity` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `created_at` DATE NOT NULL,
  `Air Company_id` INT NOT NULL,
  PRIMARY KEY (`idAirplane`),
  INDEX `fk_Airplane_Air Company_idx` (`Air Company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airplane_Air Company`
    FOREIGN KEY (`Air Company_id`)
    REFERENCES `synergy`.`Air Company` (`idAir Company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `synergy`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `synergy`.`Flight` (
  `idFlight` INT NOT NULL AUTO_INCREMENT,
  `flight_status` VARCHAR(45) NOT NULL,
  `departure_country` VARCHAR(45) NOT NULL,
  `destination_country` VARCHAR(45) NOT NULL,
  `distance` INT NOT NULL,
  `estimated_flight_time` TIME NOT NULL,
  `ended_at` TIME NOT NULL,
  `delay_started_at` TIME NULL DEFAULT 'without flight delay',
  `created_at` TIMESTAMP NOT NULL,
  `Airplane_idAirplane` INT NOT NULL,
  `Air Company_idAir Company` INT NOT NULL,
  PRIMARY KEY (`idFlight`),
  INDEX `fk_Flight_Airplane1_idx` (`Airplane_idAirplane` ASC) VISIBLE,
  INDEX `fk_Flight_Air Company1_idx` (`Air Company_idAir Company` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_Airplane1`
    FOREIGN KEY (`Airplane_idAirplane`)
    REFERENCES `synergy`.`Airplane` (`idAirplane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Air Company1`
    FOREIGN KEY (`Air Company_idAir Company`)
    REFERENCES `synergy`.`Air Company` (`idAir Company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
